"""Render the quantitative datasets as Markdown -> dossier/12..14.

Research notebooks ingest prose reliably and CSV unreliably: a .csv URL is often
rejected outright, and when it is accepted the header row may not survive as
column semantics. So the same numbers are also published as Markdown — a summary
block that states the derived result up front, then the full table underneath so
nothing is lost.

    python tools/export_tables.py

Generated. Edit the fetchers or the canonical data in data/, never these.
"""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dossier")


def load(n):
    with io.open(os.path.join(ROOT, "data", n), encoding="utf-8") as f:
        return json.load(f)


def write(name, text):
    with io.open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    print("  %-36s %7d words  %6d KB"
          % (name, len(text.split()), os.path.getsize(os.path.join(OUT, name)) // 1024))


def fireballs():
    d = load("fireballs.json")
    ev = d["events"]
    yrs = {}
    for e in ev:
        y = e[0][:4]
        s = yrs.setdefault(y, [0, 0, 0])
        s[0] += 1
        if (e[2] or 0) >= 1:
            s[1] += 1
        if (e[2] or 0) >= 5:
            s[2] += 1

    L = ["# CNEOS Fireballs — full table\n",
         "> GENERATED by `tools/export_tables.py`. Same data as `07-cneos-fireballs.csv`.\n",
         "NASA/JPL Center for Near-Earth Object Studies atmospheric impact record.",
         "**%d events, %s to %s**, of which %d report a position.\n"
         % (d["count"], d["first"], d["last"], d["located"]),
         "## Read this before using the numbers\n",
         "- **`impact_energy_kt` is the analytic column.** `radiated_energy_1e10J` is the",
         "  light emitted only, and the two differ by roughly an order of magnitude. They are",
         "  routinely quoted interchangeably in public discussion; they are not the same thing.",
         "- **CNEOS publishes no uncertainties on any field.** Not on energy, position, altitude",
         "  or velocity. Most disputes about this catalog reduce to that fact.",
         "- **Detection floor ~0.048 kt.** The smallest event in the record. Only 6 of %d rows"
         % d["count"],
         "  fall below 0.073 kt. Absence of a row is NOT evidence an event did not happen.",
         "- **The yearly count is not a measurement of the sky.** The satellite record begins",
         "  in the mid-1990s; pre-1994 years are years with almost no reporting, not quiet years.",
         "- **`velocity_km_s` is present for a minority of rows only.**\n",
         "## Events per year\n",
         "| Year | All events | >= 1 kt | >= 5 kt |", "|---|---|---|---|"]
    for y in sorted(yrs):
        s = yrs[y]
        L.append("| %s | %d | %d | %d |" % (y, s[0], s[1], s[2]))

    L += ["", "## Full event table\n",
          "Blank cells are values CNEOS does not report for that row.\n",
          "| Date (UTC) | Impact energy (kt) | Radiated (1e10 J) | Lat (N) | Lon (E) | Alt (km) | Vel (km/s) | Tag |",
          "|---|---|---|---|---|---|---|---|"]
    for e in ev:
        L.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
            e[0], e[2] if e[2] is not None else "",
            e[1] if e[1] is not None else "",
            e[3] if e[3] is not None else "", e[4] if e[4] is not None else "",
            e[5] if e[5] is not None else "", e[6] if e[6] is not None else "",
            e[7] or ""))
    write("12-cneos-fireballs.md", "\n".join(L) + "\n")


def ams():
    d = load("ams-reports.json")
    keys = [b["key"] for b in d["bins"]]
    labels = dict((b["key"], b["label"]) for b in d["bins"])
    years = sorted(d["years"], key=int)

    def tot(y, k, n=12):
        return sum((d["years"][y].get(k) or [0] * 12)[:n])

    L = ["# AMS Eyewitness Fireball Reports — full table\n",
         "> GENERATED by `tools/export_tables.py`. Same data as `08-ams-reports.csv`.\n",
         "American Meteor Society / IMO public statistics: events per month, binned by",
         "**how many people reported each event**. %s-%s.\n" % (years[0], years[-1]),
         "## Read this before using the numbers\n",
         "- **The unit is PEOPLE, not photons.** This measures attention, not brightness.",
         "  It rises with population, phone cameras, social reach and time of night.",
         "- **Raw counts are NOT comparable across years.** The reporting audience grew",
         "  throughout. Use each bin as a SHARE of that year's total.",
         "- **A growing audience pushes events UPWARD through the bins**, because each event",
         "  collects more reports. An event drawing 20 reports in 2022 draws 45 in 2026 and",
         "  leaves the 11-25 band. So a flat middle band is the signature of the bias, not",
         "  evidence against it.",
         "- **The diagnostic that matters:** did well-witnessed events outgrow the dataset as",
         "  a whole? For Q1 2026 they did not (x1.21 against x1.23 for all events).\n",
         "## Bin definitions\n", "| Key | Definition |", "|---|---|"]
    for k in keys:
        L.append("| `%s` | %s |" % (k, labels[k]))

    L += ["", "## Annual totals by bin\n",
          "| Year | " + " | ".join(labels[k].replace("Events with ", "") for k in keys) +
          " | Total | >=51 as % of total |",
          "|---" * (len(keys) + 3) + "|"]
    for y in years:
        row = [tot(y, k) for k in keys]
        t = sum(row)
        big = tot(y, "51_99") + tot(y, "100_plus")
        L.append("| %s | %s | %d | %s |" % (
            y, " | ".join(str(v) for v in row), t,
            ("%.3f%%" % (100.0 * big / t)) if t else "—"))

    MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
              "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    L += ["", "## Monthly detail, by bin\n",
          "Zero in a trailing month of the most recent year means *not yet occurred*, not *no events*.\n"]
    for k in keys:
        L += ["", "### %s (`%s`)\n" % (labels[k], k),
              "| Year | " + " | ".join(MONTHS) + " | Total |",
              "|---" * 14 + "|"]
        for y in years:
            m = d["years"][y].get(k) or [0] * 12
            L.append("| %s | %s | %d |" % (y, " | ".join(str(v) for v in m), sum(m)))
    write("13-ams-reports.md", "\n".join(L) + "\n")


def gmn():
    d = load("gmn-monthly.json")
    M = {k: v for k, v in d["months"].items() if v}
    L = ["# Global Meteor Network — monthly photometry\n",
         "> GENERATED by `tools/export_tables.py`. Same data as `09-gmn-monthly.csv`.\n",
         "Camera-measured meteor trajectories with **absolute magnitudes**. No human decides",
         "whether an event is filed, which is what makes this the tiebreaker instrument.",
         "**%d months, %s to %s.**\n" % (len(M), min(M), max(M)),
         "## Read this before using the numbers\n",
         "- **The network grew from 9 stations to over 1,300.** Raw meteor counts across years",
         "  measure the network, not the sky. This is the same trap as the pre-1994 CNEOS years.",
         "- **`bright_pct` is the comparable statistic**: meteors at absolute magnitude <= -4 as",
         "  a share of all detections. More cameras multiply faint and bright together, so the",
         "  ratio holds; a real excess of bright meteors moves it.",
         "- **`median_absmag` is the sensitivity-drift check.** If cameras grew more sensitive,",
         "  fainter detections would swell the denominator and MASK a real rise. It holds",
         "  between -0.09 and +0.05 across 2021-2026, so the confound does not apply.",
         "- **GMN is night-blind**, and its coverage is concentrated in Europe and North",
         "  America. It cannot speak to daytime bolides at all.\n",
         "## Annual summary\n",
         "| Year | Meteors | Peak stations | mag <= -4 | Bright % | Median AbsMag |",
         "|---|---|---|---|---|---|"]
    for y in sorted({k[:4] for k in M}):
        ms = [v for k, v in M.items() if k[:4] == y]
        n = sum(v["n"] for v in ms)
        b = sum(v["counts"]["m4"] for v in ms)
        med = sum(v["median_absmag"] for v in ms) / len(ms)
        L.append("| %s | %d | %d | %d | %.4f%% | %+.2f |"
                 % (y, n, max(v["stations"] for v in ms), b,
                    100.0 * b / n if n else 0, med))

    L += ["", "## Monthly detail\n",
          "| Month | Meteors | Stations | Median AbsMag | <=0 | <=-2 | <=-4 | <=-6 | Bright % |",
          "|---|---|---|---|---|---|---|---|---|"]
    for k in sorted(M):
        v = M[k]
        c = v["counts"]
        L.append("| %s-%s | %d | %d | %+.2f | %d | %d | %d | %d | %.4f%% |"
                 % (k[:4], k[4:], v["n"], v["stations"], v["median_absmag"],
                    c["m0"], c["m2"], c["m4"], c["m6"],
                    100.0 * c["m4"] / v["n"] if v["n"] else 0))
    write("14-gmn-monthly.md", "\n".join(L) + "\n")


def main():
    os.makedirs(OUT, exist_ok=True)
    fireballs(); ams(); gmn()
    return 0


if __name__ == "__main__":
    sys.exit(main())
