"""Export the whole corpus as readable Markdown + CSV -> dossier/.

Pointing a research notebook at data/*.json technically shares the data and
practically shares very little: a language model reading 1,069 positional arrays
gets almost nothing out of them, and the case corpus is buried inside JSON string
fields where it cannot be quoted or cited cleanly.

This writes the same content as documents. Prose becomes Markdown with headings
and citations; tabular data becomes CSV with real column names. The result is
what a notebook can actually reason over, and it is regenerated from the same
canonical files so the two can never drift.

    python tools/export_dossier.py

Everything under dossier/ is GENERATED. Never hand-edit it; edit the source in
data/ and re-run.
"""
import csv, io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dossier")

OBJ_NAME = {"3i": "3I/ATLAS (C/2025 N1)", "1i": "1I/'Oumuamua (1I/2017 U1)",
            "2i": "2I/Borisov (C/2019 Q4)", "fb": "CNEOS fireball register"}


def load(name):
    p = os.path.join(ROOT, "data", name)
    if not os.path.exists(p):
        sys.exit("Missing data/%s" % name)
    with io.open(p, encoding="utf-8") as f:
        return json.load(f)


def write(name, text):
    with io.open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    n = len(text.split())
    print("  %-34s %7d words" % (name, n))
    return n


def case_md(c, obj):
    """One case as a document section. Both readings stay adjacent and labelled:
    pulling a sentence out of one without the other inverts the meaning, and a
    notebook WILL pull sentences out."""
    L = []
    L.append("### %s — %s\n" % (c.get("id"), c.get("title")))
    L.append("- **Object:** %s" % OBJ_NAME.get(obj, obj))
    L.append("- **Date:** %s" % (c.get("date") or "—"))
    L.append("- **Verification:** `%s`" % (c.get("_verify") or c.get("verify") or "UNCHECKED"))
    if c.get("loeb_scale") is not None:
        L.append("- **Loeb Scale (third-party rank):** %s" % c["loeb_scale"])
    L.append("")
    if c.get("observation"):
        L.append("**OBSERVATION — what was measured**\n\n%s\n" % c["observation"])
    if c.get("loeb_take"):
        L.append("**CLAIM — the anomaly / technosignature reading**\n\n%s\n" % c["loeb_take"])
    if c.get("loeb_quote"):
        L.append("> %s\n>\n> — %s\n" % (c["loeb_quote"], c.get("quote_source") or "source not recorded"))
    if c.get("official_explanation"):
        L.append("**COUNTER-READING — the mainstream explanation**\n\n%s\n"
                 % c["official_explanation"])
    if c.get("_verifyNotes"):
        L.append("**Verification notes:** %s\n" % c["_verifyNotes"])
    if c.get("sources"):
        L.append("**Sources:** " + " · ".join("<%s>" % u for u in c["sources"]) + "\n")
    return "\n".join(L)


def header(title, note):
    return ("# %s\n\n> GENERATED by `tools/export_dossier.py` from the canonical data in\n"
            "> `data/`. Do not hand-edit. %s\n\n---\n\n" % (title, note))


def main():
    os.makedirs(OUT, exist_ok=True)
    d3, diso = load("research.json"), load("research-iso.json")
    fbc, brf = load("fireball-cases.json"), load("briefings.json")
    fb = load("fireballs.json")
    total = 0

    # --- cases -------------------------------------------------------------
    body = header("3I/ATLAS — Case Files",
                  "Every case carries the claim AND its counter-reading; the two are adjacent "
                  "by design and a sentence taken from one alone will read as the project's "
                  "own position when it is not.")
    body += "%d cases. Verification vocabulary: `CONFIRMED` = matched the primary source " \
            "unchanged; `CORRECTED` = an error was found and fixed before publication.\n\n" \
            % len(d3["anomalies"])
    body += "\n".join(case_md(c, "3i") for c in d3["anomalies"])
    total += write("01-cases-3i-atlas.md", body)

    body = header("1I/'Oumuamua and 2I/Borisov — Case Files",
                  "2I/Borisov is the CONTROL CASE: an interstellar object that behaved "
                  "entirely like an ordinary comet. Its file is thin on purpose.")
    body += "\n".join(case_md(c, "1i") for c in diso.get("anomalies1i", []))
    body += "\n".join(case_md(c, "2i") for c in diso.get("anomalies2i", []))
    total += write("02-cases-oumuamua-borisov.md", body)

    body = header("CNEOS Fireball Register — Case Files",
                  "Analyses computed from the shipped datasets rather than from published "
                  "papers. Every figure quoted is re-derived by tools/fireball_rate_check.py.")
    body += "\n".join(case_md(c, "fb") for c in fbc["cases"])
    total += write("03-cases-fireballs.md", body)

    # --- briefings ---------------------------------------------------------
    body = header("Briefings — Question-Led Syntheses",
                  "The interpretive layer: each answers one question and names the case files "
                  "underneath it.")
    for b in brf["briefings"]:
        body += "## %s — %s\n\n**Short answer:** %s\n\n" % (b["id"], b["question"], b["short"])
        for s in b["sections"]:
            body += "### %s\n\n%s\n\n" % (s["h"], s["p"])
        body += "**Case files behind this:** %s\n\n" % ", ".join(b.get("cases", []) or ["—"])
        if b.get("sources"):
            body += "**Sources:** " + " · ".join("<%s>" % u for u in b["sources"]) + "\n\n---\n\n"
    total += write("04-briefings.md", body)

    # --- timeline ----------------------------------------------------------
    body = header("Timeline — All Objects",
                  "Chronological record. `kind` is one of discovery, observation, "
                  "close_approach, statement, status.")
    for label, payload, key in (("3I/ATLAS", d3, "timeline"),
                                ("1I/'Oumuamua", diso, "timeline1i"),
                                ("2I/Borisov", diso, "timeline2i")):
        evs = (payload.get(key) or {}).get("events", [])
        body += "## %s — %d events\n\n" % (label, len(evs))
        for e in sorted(evs, key=lambda x: x.get("date") or ""):
            body += "### %s — %s\n\n- **kind:** `%s`\n\n%s\n\n" % (
                e.get("date"), e.get("title"), e.get("kind") or "—", e.get("description") or "")
            if e.get("sources"):
                body += "**Sources:** " + " · ".join("<%s>" % u for u in e["sources"]) + "\n\n"
    total += write("05-timeline.md", body)

    # --- quotes ------------------------------------------------------------
    body = header("Quotations",
                  "`verify` states how each was checked. SECONDARY means the primary text is "
                  "not publicly fetchable — it is labelled, not presented as verified.")
    qs = list((d3.get("quotes") or {}).get("quotes", [])) + \
         list((diso.get("quotes") or {}).get("quotes", []))
    body += "%d quotations.\n\n| Speaker | Date | Camp | Verify | Quote | Source |\n" % len(qs)
    body += "|---|---|---|---|---|---|\n"
    for q in qs:
        txt = (q.get("text") or "").replace("|", "\\|").replace("\n", " ")
        body += "| %s | %s | %s | `%s` | %s | %s |\n" % (
            q.get("speaker") or "—", q.get("date") or "—", q.get("camp") or "—",
            q.get("verify") or "SECONDARY", txt, (q.get("source") or "—").replace("|", "\\|"))
    total += write("06-quotations.md", body)

    # --- CSVs --------------------------------------------------------------
    path = os.path.join(OUT, "07-cneos-fireballs.csv")
    with io.open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["date_utc", "radiated_energy_1e10J", "impact_energy_kt",
                    "latitude_deg_N", "longitude_deg_E", "altitude_km",
                    "velocity_km_s", "tag"])
        for e in fb["events"]:
            w.writerow(e)
    print("  %-34s %7d rows" % ("07-cneos-fireballs.csv", len(fb["events"])))

    ams = load("ams-reports.json")
    path = os.path.join(OUT, "08-ams-reports.csv")
    with io.open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["year", "month", "bin", "bin_definition", "events"])
        defs = dict((b["key"], b["label"]) for b in ams["bins"])
        n = 0
        for y in sorted(ams["years"]):
            for k, months in ams["years"][y].items():
                for m, v in enumerate(months, 1):
                    w.writerow([y, m, k, defs.get(k, k), v]); n += 1
    print("  %-34s %7d rows" % ("08-ams-reports.csv", n))

    gmn = load("gmn-monthly.json")
    path = os.path.join(OUT, "09-gmn-monthly.csv")
    with io.open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["year_month", "meteors", "stations", "median_absmag",
                    "n_mag_le_0", "n_mag_le_-2", "n_mag_le_-4", "n_mag_le_-6",
                    "bright_fraction_mag_le_-4_pct"])
        n = 0
        for k in sorted(gmn["months"]):
            v = gmn["months"][k]
            if not v:
                continue
            c = v["counts"]
            w.writerow([k, v["n"], v["stations"], v["median_absmag"],
                        c["m0"], c["m2"], c["m4"], c["m6"],
                        round(100.0 * c["m4"] / v["n"], 4)]); n += 1
    print("  %-34s %7d rows" % ("09-gmn-monthly.csv", n))

    # --- spatial test ------------------------------------------------------
    sp = load("spatial-test.json")
    body = header("Spatial Test — Fireball / Volcano Proximity",
                  "Monte Carlo output. The null model is the test; see section 4.6 of the "
                  "dossier for why a uniform-random null would be wrong here.")
    body += ("%d located CNEOS events against %d NOAA volcano positions, %d trials per null.\n\n"
             % (sp["events"], sp["volcanoes"], sp["trials"]))
    body += "| Within | Observed | Rotation null | p | Scatter null | p |\n|---|---|---|---|---|---|\n"
    for r in sorted(sp["radii"], key=int):
        v = sp["radii"][r]
        body += "| %s km | %d | %.1f | %.3f | %.1f | %.3f |\n" % (
            r, v["observed"], v["rotation_mean"], v["rotation_p"],
            v["scatter_mean"], v["scatter_p"])
    m = sp["median"]
    body += ("| median nearest volcano | %.0f km | %.0f km | %.3f | %.0f km | %.3f |\n\n"
             % (m["observed"], m["rotation_mean"], m["rotation_p"],
                m["scatter_mean"], m["scatter_p"]))
    c = sp["cluster"]
    body += ("### Clustering (scatter null only — a rotation leaves every event-to-event "
             "distance unchanged and cannot test this)\n\n")
    body += "| Statistic | Observed | Null mean | p |\n|---|---|---|---|\n"
    body += "| median nearest-event distance | %.0f km | %.0f km | %.3f |\n" % (
        c["median_nn"]["observed"], c["median_nn"]["null_mean"], c["median_nn"]["p"])
    for k, lbl in (("pairs_100", "events with another within 100 km"),
                   ("pairs_50", "events with another within 50 km")):
        body += "| %s | %d | %.1f | %.3f |\n" % (lbl, c[k]["observed"], c[k]["null_mean"], c[k]["p"])
    h = sp["histogram"]
    body += "\n### Distance histogram (100 km bins)\n\n| Bin start (km) | Observed | Expected by chance |\n|---|---|---|\n"
    for b, o, nl in zip(h["bins"], h["observed"], h["null_mean"]):
        body += "| %d | %d | %.1f |\n" % (b, o, nl)
    total += write("10-spatial-test.md", body)

    # --- comparison --------------------------------------------------------
    comp = (d3.get("comparison") or {}).get("objects", [])
    if comp:
        body = header("Three-Object Comparison", "Profiles used by the COMPARE view.")
        for o in comp:
            body += "## %s\n\n" % (o.get("name") or o.get("object") or "?")
            for k, v in o.items():
                if k in ("name", "object"):
                    continue
                body += "- **%s:** %s\n" % (k, v)
            body += "\n"
        total += write("11-comparison-profiles.md", body)

    # --- start-here manifest, generated so its counts cannot go stale ------
    files = []
    for fn in sorted(os.listdir(OUT)):
        if fn.startswith("00-"):
            continue
        fp = os.path.join(OUT, fn)
        size = os.path.getsize(fp)
        if fn.endswith(".csv"):
            with io.open(fp, encoding="utf-8") as f:
                rows = sum(1 for _ in f) - 1
            files.append((fn, "CSV", size, "%d rows" % rows))
        else:
            with io.open(fp, encoding="utf-8") as f:
                words = len(f.read().split())
            files.append((fn, "Markdown", size, "%d words" % words))

    man = ["# START HERE — 3I/ATLAS corpus for a research notebook\n",
           "> GENERATED by `tools/export_dossier.py`. Everything in this folder is exported",
           "> from the canonical data in `data/`, so it cannot drift from the live project.\n",
           "This folder is the whole analysable corpus as documents. Ingest these rather than",
           "the raw JSON in `data/`: the JSON is the machine format, and a notebook reading",
           "1,069 positional arrays gets almost nothing from them.\n",
           "## Files\n",
           "| File | Format | Size | Extent |", "|---|---|---|---|"]
    for fn, fmt, size, ext in files:
        man.append("| `%s` | %s | %d KB | %s |" % (fn, fmt, max(1, size // 1024), ext))

    man += ["",
      "## Ingest in this order",
      "",
      "1. **`04-briefings.md`** — six question-led syntheses. Highest density; establishes",
      "   what the project found and the vocabulary the rest uses.",
      "2. **`10-spatial-test.md`** — the statistical method, worked. Short, and it explains",
      "   why the null model matters before any raw count is read.",
      "3. **`01`–`03` case files** — the 47 records, each carrying a claim and its",
      "   counter-reading in adjacent labelled blocks.",
      "4. **`05-timeline.md`, `06-quotations.md`, `11-comparison-profiles.md`** — supporting record.",
      "5. **`07`–`09` CSVs** — the quantitative substrate. Ingest LAST: without the",
      "   normalisation rules from steps 1-2 in context, raw counts read as trends.",
      "",
      "## Four things a notebook will get wrong unless told",
      "",
      "1. **Raw counts in `08` and `09` are not comparable across years.** The camera network",
      "   grew from 9 stations to over 1,300 and the eyewitness audience grew with it. Use",
      "   `bright_fraction_mag_le_-4_pct` in `09`, and shares rather than counts in `08`.",
      "2. **`impact_energy_kt` is the analytic column in `07`**, not `radiated_energy_1e10J`.",
      "   They differ by roughly an order of magnitude and are routinely confused in public",
      "   discussion of these events.",
      "3. **`CORRECTED` in a verification field means found-wrong-and-fixed**, so the record is",
      "   now accurate. It is the majority state, and it is not a confidence downgrade.",
      "4. **Every case file states a claim AND its rebuttal in adjacent blocks.** A sentence",
      "   quoted from the CLAIM block alone will read as the project's own position when it",
      "   is the opposite. Always carry the block heading with the quote.",
      "",
      "## Not included",
      "",
      "The video transcripts that are the claim source are third-party content held in a",
      "separate private repository, and are not here. Case files quote them only in short",
      "attributed excerpts, always labelled as auto-caption derived rather than as published",
      "text.",
      ""]
    write("00-START-HERE.md", "\n".join(man))

    print("\n%d markdown words + 3 CSVs in %s" % (total, OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
