"""Render the quantitative datasets as Markdown -> dossier/12..15.

Research notebooks ingest prose reliably and CSV unreliably: a .csv URL is often
rejected outright, and when it is accepted the header row may not survive as
column semantics. So the same numbers are also published as Markdown — a summary
block that states the derived result up front, then the full table underneath so
nothing is lost.

    python tools/export_tables.py

Generated. Edit the fetchers or the canonical data in data/, never these.
"""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dossier")


def load(n):
    with io.open(os.path.join(ROOT, "data", n), encoding="utf-8") as f:
        return json.load(f)


def write(name, text):
    with io.open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(text)
    print("  %-36s %7d words  %6d KB"
          % (name, len(text.split()), os.path.getsize(os.path.join(OUT, name)) // 1024))


def fireballs():
    d = load("fireballs.json")
    ev = d["events"]
    yrs = {}
    for e in ev:
        y = e[0][:4]
        s = yrs.setdefault(y, [0, 0, 0])
        s[0] += 1
        if (e[2] or 0) >= 1:
            s[1] += 1
        if (e[2] or 0) >= 5:
            s[2] += 1

    L = ["# CNEOS Fireballs — full table\n",
         "> GENERATED by `tools/export_tables.py`. Same data as `07-cneos-fireballs.csv`.\n",
         "NASA/JPL Center for Near-Earth Object Studies atmospheric impact record.",
         "**%d events, %s to %s**, of which %d report a position.\n"
         % (d["count"], d["first"], d["last"], d["located"]),
         "## Read this before using the numbers\n",
         "- **`impact_energy_kt` is the analytic column.** `radiated_energy_1e10J` is the",
         "  light emitted only, and the two differ by roughly an order of magnitude. They are",
         "  routinely quoted interchangeably in public discussion; they are not the same thing.",
         "- **CNEOS publishes no uncertainties on any field.** Not on energy, position, altitude",
         "  or velocity. Most disputes about this catalog reduce to that fact.",
         "- **Detection floor ~0.048 kt.** The smallest event in the record. Only 6 of %d rows"
         % d["count"],
         "  fall below 0.073 kt. Absence of a row is NOT evidence an event did not happen.",
         "- **The yearly count is not a measurement of the sky.** The satellite record begins",
         "  in the mid-1990s; pre-1994 years are years with almost no reporting, not quiet years.",
         "- **`velocity_km_s` is present for a minority of rows only.**\n",
         "## Events per year\n",
         "| Year | All events | >= 1 kt | >= 5 kt |", "|---|---|---|---|"]
    for y in sorted(yrs):
        s = yrs[y]
        L.append("| %s | %d | %d | %d |" % (y, s[0], s[1], s[2]))

    L += ["", "## Full event table\n",
          "Blank cells are values CNEOS does not report for that row.\n",
          "| Date (UTC) | Impact energy (kt) | Radiated (1e10 J) | Lat (N) | Lon (E) | Alt (km) | Vel (km/s) | Tag |",
          "|---|---|---|---|---|---|---|---|"]
    for e in ev:
        L.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
            e[0], e[2] if e[2] is not None else "",
            e[1] if e[1] is not None else "",
            e[3] if e[3] is not None else "", e[4] if e[4] is not None else "",
            e[5] if e[5] is not None else "", e[6] if e[6] is not None else "",
            e[7] or ""))
    write("12-cneos-fireballs.md", "\n".join(L) + "\n")


def ams():
    d = load("ams-reports.json")
    keys = [b["key"] for b in d["bins"]]
    labels = dict((b["key"], b["label"]) for b in d["bins"])
    years = sorted(d["years"], key=int)

    def tot(y, k, n=12):
        return sum((d["years"][y].get(k) or [0] * 12)[:n])

    L = ["# AMS Eyewitness Fireball Reports — full table\n",
         "> GENERATED by `tools/export_tables.py`. Same data as `08-ams-reports.csv`.\n",
         "American Meteor Society / IMO public statistics: events per month, binned by",
         "**how many people reported each event**. %s-%s.\n" % (years[0], years[-1]),
         "## Read this before using the numbers\n",
         "- **The unit is PEOPLE, not photons.** This measures attention, not brightness.",
         "  It rises with population, phone cameras, social reach and time of night.",
         "- **Raw counts are NOT comparable across years.** The reporting audience grew",
         "  throughout. Use each bin as a SHARE of that year's total.",
         "- **A growing audience pushes events UPWARD through the bins**, because each event",
         "  collects more reports. An event drawing 20 reports in 2022 draws 45 in 2026 and",
         "  leaves the 11-25 band. So a flat middle band is the signature of the bias, not",
         "  evidence against it.",
         "- **The diagnostic that matters:** did well-witnessed events outgrow the dataset as",
         "  a whole? For Q1 2026 they did not (x1.21 against x1.23 for all events).\n",
         "## Bin definitions\n", "| Key | Definition |", "|---|---|"]
    for k in keys:
        L.append("| `%s` | %s |" % (k, labels[k]))

    L += ["", "## Annual totals by bin\n",
          "| Year | " + " | ".join(labels[k].replace("Events with ", "") for k in keys) +
          " | Total | >=51 as % of total |",
          "|---" * (len(keys) + 3) + "|"]
    for y in years:
        row = [tot(y, k) for k in keys]
        t = sum(row)
        big = tot(y, "51_99") + tot(y, "100_plus")
        L.append("| %s | %s | %d | %s |" % (
            y, " | ".join(str(v) for v in row), t,
            ("%.3f%%" % (100.0 * big / t)) if t else "—"))

    MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
              "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    L += ["", "## Monthly detail, by bin\n",
          "Zero in a trailing month of the most recent year means *not yet occurred*, not *no events*.\n"]
    for k in keys:
        L += ["", "### %s (`%s`)\n" % (labels[k], k),
              "| Year | " + " | ".join(MONTHS) + " | Total |",
              "|---" * 14 + "|"]
        for y in years:
            m = d["years"][y].get(k) or [0] * 12
            L.append("| %s | %s | %d |" % (y, " | ".join(str(v) for v in m), sum(m)))
    write("13-ams-reports.md", "\n".join(L) + "\n")


def gmn():
    d = load("gmn-monthly.json")
    M = {k: v for k, v in d["months"].items() if v}
    L = ["# Global Meteor Network — monthly photometry\n",
         "> GENERATED by `tools/export_tables.py`. Same data as `09-gmn-monthly.csv`.\n",
         "Camera-measured meteor trajectories with **absolute magnitudes**. No human decides",
         "whether an event is filed, which is what makes this the tiebreaker instrument.",
         "**%d months, %s to %s.**\n" % (len(M), min(M), max(M)),
         "## Read this before using the numbers\n",
         "- **The network grew from 9 stations to over 1,300.** Raw meteor counts across years",
         "  measure the network, not the sky. This is the same trap as the pre-1994 CNEOS years.",
         "- **`bright_pct` is the comparable statistic**: meteors at absolute magnitude <= -4 as",
         "  a share of all detections. More cameras multiply faint and bright together, so the",
         "  ratio holds; a real excess of bright meteors moves it.",
         "- **`median_absmag` is the sensitivity-drift check.** If cameras grew more sensitive,",
         "  fainter detections would swell the denominator and MASK a real rise. It holds",
         "  between -0.09 and +0.05 across 2021-2026, so the confound does not apply.",
         "- **GMN is night-blind**, and its coverage is concentrated in Europe and North",
         "  America. It cannot speak to daytime bolides at all.\n",
         "## Annual summary\n",
         "| Year | Meteors | Peak stations | mag <= -4 | Bright % | Median AbsMag |",
         "|---|---|---|---|---|---|"]
    for y in sorted({k[:4] for k in M}):
        ms = [v for k, v in M.items() if k[:4] == y]
        n = sum(v["n"] for v in ms)
        b = sum(v["counts"]["m4"] for v in ms)
        med = sum(v["median_absmag"] for v in ms) / len(ms)
        L.append("| %s | %d | %d | %d | %.4f%% | %+.2f |"
                 % (y, n, max(v["stations"] for v in ms), b,
                    100.0 * b / n if n else 0, med))

    L += ["", "## Monthly detail\n",
          "| Month | Meteors | Stations | Median AbsMag | <=0 | <=-2 | <=-4 | <=-6 | Bright % |",
          "|---|---|---|---|---|---|---|---|---|"]
    for k in sorted(M):
        v = M[k]
        c = v["counts"]
        L.append("| %s-%s | %d | %d | %+.2f | %d | %d | %d | %d | %.4f%% |"
                 % (k[:4], k[4:], v["n"], v["stations"], v["median_absmag"],
                    c["m0"], c["m2"], c["m4"], c["m6"],
                    100.0 * c["m4"] / v["n"] if v["n"] else 0))
    write("14-gmn-monthly.md", "\n".join(L) + "\n")


def nuforc():
    d = load("nuforc.json")
    ms = {m["m"]: m for m in d["months"]}
    order = sorted(ms, key=lambda k: -(100.0 * ms[k]["fb"] / ms[k]["n"] if ms[k]["n"] else 0))
    claim = d["claim"]["month"]
    through = d["claim"]["through_day"]
    ct = sum(x["n"] for x in d["claim"]["days"][:through])
    cf = sum(x["fb"] for x in d["claim"]["days"][:through])

    L = ["# NUFORC sightings — fireball share by month\n",
         "> GENERATED by `tools/export_tables.py` from `data/nuforc.json`.\n",
         "National UFO Reporting Center sighting archive, as geocoded and time-normalised by",
         "the planetsig/ufo-reports mirror in 2014. **%d reports, %s to %s**, of which %d carry"
         % (d["rows"], d["first_sighting"], d["last_sighting"], d["shaped"]),
         "a shape label and %d do not.\n" % d["unlabelled"],
         "## Read this before using the numbers\n",
         "- **`shape` is what the WITNESS called it.** It is a self-assigned label picked from a",
         "  fixed list, not a measurement. 'Fireball' here is not the same quantity AMS or CNEOS",
         "  report under that name, and the two must not be compared directly.",
         "- **The mirror is SCRUBBED.** Its unscrubbed set is documented at 88,874 records; the",
         "  file read here holds %d, rows with an unresolvable location or unparseable duration" % d["rows"],
         "  having been dropped. Counts run below NUFORC's own, unevenly across time.",
         "- **It STOPS at %s.** Nothing after that date can be tested against it." % d["last_sighting"],
         "- **It is %.0f%% United States.** On 2013-02-15, the day of the Chelyabinsk airburst,"
         % (100.0 * next((c["n"] for c in d["countries"] if c["c"] == "us"), 0) / d["rows"]),
         "  the archive logged %d reports, %d of them fireball — the largest airburst since"
         % (d["chelyabinsk"]["n"], d["chelyabinsk"]["fb"]),
         "  Tunguska is essentially absent from it, because it happened abroad.",
         "- **Every share below is over shape-bearing rows.** Unlabelled rows are excluded from",
         "  shares and counted separately.\n",
         "## The derived result\n",
         "Fireball is **%d of %d shape-bearing reports (%.2f%%)** and ranks **%d of %d shapes**."
         % (d["fireball"]["count"], d["shaped"], d["fireball"]["share"],
            d["fireball"]["rank"], d["fireball"]["shapes"]),
         "In %s through the %dth the archive holds %d reports with %d fireballs (%.2f%%), and"
         % (claim, through, ct, cf, 100.0 * cf / ct if ct else 0),
         "%.2f%% for the whole month — against %.2f%% for the twelve months immediately before it."
         % (100.0 * ms[claim]["fb"] / ms[claim]["n"],
            100.0 * sum(ms[k]["fb"] for k in ms if "2012-11" <= k <= "2013-10")
            / sum(ms[k]["n"] for k in ms if "2012-11" <= k <= "2013-10")),
         "It ranks **%d of the %d months** in the window; the record is %s at %.2f%%.\n"
         % (1 + order.index(claim), len(ms), order[0],
            100.0 * ms[order[0]]["fb"] / ms[order[0]]["n"]),
         "## Shape distribution, whole archive\n",
         "| Shape | Reports | Share |", "|---|---|---|"]
    for x in d["shapes"]:
        L.append("| %s | %d | %.2f%% |" % (x["shape"], x["n"], x["share"]))

    L += ["", "## Annual fireball share\n",
          "| Year | Shape-bearing | Fireball | Share |", "|---|---|---|---|"]
    for y in d["years"]:
        L.append("| %d | %d | %d | %.2f%% |"
                 % (y["y"], y["n"], y["fb"], 100.0 * y["fb"] / y["n"] if y["n"] else 0))

    L += ["", "## Fireball share by calendar month, 2000-2013\n",
          "The July and December peaks are the Perseids and the Geminids appearing in a",
          "database of public shape guesses — evidence the label carries real signal.\n",
          "| Month | Shape-bearing | Fireball | Share |", "|---|---|---|---|"]
    for x in d["seasonal"]:
        L.append("| %02d | %d | %d | %.2f%% |"
                 % (x["m"], x["n"], x["fb"], 100.0 * x["fb"] / x["n"] if x["n"] else 0))

    L += ["", "## Monthly detail\n",
          "| Month | Shape-bearing | Fireball | Share |", "|---|---|---|---|"]
    for k in sorted(ms):
        v = ms[k]
        L.append("| %s | %d | %d | %.2f%% |"
                 % (k, v["n"], v["fb"], 100.0 * v["fb"] / v["n"] if v["n"] else 0))
    write("15-nuforc-sightings.md", "\n".join(L) + "\n")


def main():
    os.makedirs(OUT, exist_ok=True)
    fireballs(); ams(); gmn(); nuforc()
    return 0


if __name__ == "__main__":
    sys.exit(main())
